use std::f32::consts::PI;

pub const WANDER_DEFAULT_BASE_VARIATION: f32 = PI * 0.5;
pub const WANDER_DEFAULT_ACCEL_MULTIPLIER: f32 = 0.1;
pub const WANDER_MIN_ACCEL_MULTIPLIER: f32 = 0.01;
pub const WANDER_MAX_ACCEL_MULTIPLIER: f32 = 0.10;
pub const WANDER_ACCEL_VARIATION_RATE: f32 = 0.05;
pub const WANDER_TURN_VARIATION_RATE: f32 = 2.0;

pub const DEFAULT_PUSH_WEIGHT: f32 = 2.0;
